### ISSUE TITLE
app.module appRoutes for multiple modules

### ISSUE THREAD

**Issue by Prinsn** [wags1999/angular-hmr-lazy-components#6]
I may be just too new to angular to understand the expected pattern, but each module of ours has its own routes defined.

how do you utilize a single `appRoutes` from the app module to populate the helper with `import { appRoutes } from "./app.module"` ? 

I'm specifically concerned with the circular dependency that I'm getting initially as our appModule itself needs the HMR.

**Comment by Prinsn** [comment]
Nvm, figured it out.  Sure someone is going to complain about moving routes out of where they were to individual files, but got it organized.

**Comment by dongyuwei** [comment]
@Prinsn @wags1999 I think a better way is change code from
```
enableHmrRouterNgModule<T>(nodeModuleRef: NodeModule, moduleRef: NgModuleRef<T>)
```

to

```
enableHmrRouterNgModule<T>(nodeModuleRef: NodeModule, moduleRef: NgModuleRef<T>, routers: Routes)
```

So we can get  routers later when we need to call `enableHmrRouterNgModule`.
