### ISSUE TITLE
HMR doesn't render changes

### ISSUE THREAD

**Issue by volago** [wags1999/angular-hmr-lazy-components#7]
Hi.

I'm trying to use this solution in complex Angular 8 application with lazy modules.

I put this code to lazy module:
```
export class SomeModule {
  constructor(moduleRef: NgModuleRef<SomeModule>) {
    HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);
  }
}

HmrModuleHelper.enableHmrNodeModule(module);
```

It seems HMR works good. In console log I see that it detect where changes were made, and reloads right module. Also component in app reloads - it display loader and then data. The rest of app doesn't change.

Only problem is that browser doesn't apply changes in component I edited. It refreshes component, but displays old HTML. Once I refresh page, then I can see new changes.

Do you have any suggestions what could it happen?

Of course your example works perfectly, even after upgraded to Angular 8 and changed lazy-loading syntax to new one.

**Comment by delphist2008** [comment]
It seems the default configuration only reload the routed components,
(https://github.com/wags1999/angular-hmr-lazy-components/issues/4)
i.e. the ones specified in @NgModule route configuration, like
```
export const routes: Routes = [{
    path: '',
    component: DashboardComponent
}];
```
You should put any other child (non-routed) components into the entryComponents section of your lazy-loaded routingModule, like this
```
// the lazy module 
@NgModule({
    imports: [
        DashboardRoutingModule
    ],
    declarations: [
        DashboardComponent,
        WidgetComponent
    ]
})
export class DashboardModule {
    constructor(moduleRef: NgModuleRef<DashboardModule>) {
        HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);
    }
}
HmrModuleHelper.enableHmrNodeModule(module);
// -----------

// the routing module
export const routes: Routes = [{
    path: '',
    component: DashboardComponent
}];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule],
    entryComponents: [
        WidgetComponent
    ]
})
export class DashboardRoutingModule {}
// -----------
```

**Comment by montella1507** [comment]
Yes you have to to let NG know they will be dynamically changed (attached / detached) - like HMR does.

**Comment by volago** [comment]
I've solved this issue. There were two problems I encountered.

**1. Routing setup**

Previously we had such routing setup, which doesn't work
```
// routing module
const routes: Routes = [
  {
    path: 'SomePath',
    component: SomeComponent
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class SomeRoutingModule { }

// lazy module
@NgModule({
  declarations: [
    ... 
  ],
  imports: [
    SomeRoutingModule,
  ],  
})
export class SomeModule { }
```

Once we changed to setup bellow, most of our lazy loaded modules started to manage HMR correctly.
```
// routing module
const routes: Routes = [
  {
    path: 'SomePath',
    component: SomeComponent
  }
];
export const routing: ModuleWithProviders = RouterModule.forChild(routes);

// lazy module
NgModule({
  declarations: [ ... ],
  imports: [
    routing,
    ...
  ]
})
export class SomeModule {
  constructor(moduleRef: NgModuleRef<SOmeModule>) {
    if (environment.hmr) {
      HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);      
    }
  }
}

if (environment.hmr) {
  HmrModuleHelper.enableHmrNodeModule(module);  
}
```

**2. Route reusing strategy**
After fixes in routing some lazy modules still didn't work. We found out that a cause was providing out own `RouteReuseStrategy`.

After all I didn't manage it to work. As workaround I disable reusing in dev mode.

**Comment by dongyuwei** [comment]
hi @volago, can you share your RouteReuseStrategy which can work with angular-hmr-lazy-components? Thanks.

**Comment by dongyuwei** [comment]
I tried to disable reusing routed components , but still don' t work.
The following is my customized RouteReuseStrategy:
```
class HMRRouteReuseStrategy extends RouteReuseStrategy {
  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }
  store(route: ActivatedRouteSnapshot, detachedTree: DetachedRouteHandle): void {}
  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return false;
  }
  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle { return null; }
  shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    return false;
  }
}
```

**Comment by volago** [comment]
Hi @dongyuwei. It is not working in my case. I implemented feature (HMR) flag. When I want HMR then I disable routing reuse strategy and vice versa.

**Comment by dongyuwei** [comment]
hi @volago , how do you disable routing reuse strategy?  In my example code , `shouldReuseRoute` always return `false`, what's the difference with your strategy?

**Comment by volago** [comment]
@dongyuwei it is done in both routing and reuse strategy.

**routing**
```typescript
{
    path: 'X',
    component: XComponent,
    data: {
      shouldReuse: !environment.hmr,
      key: 'orders-list'
    }
}
```

**strategy**

```typescript
export class CacheRouteReuseStrategy implements RouteReuseStrategy {

  handlers: { [key: string]: DetachedRouteHandle } = {};

  constructor() { }

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
    if (!route.data['shouldReuse']) {
      return null;
    }
    const c = this.handlers[route.data['key']];
    return c;
  }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    if (route.data['shouldReuse']) {
      this.handlers[route.data['key']] = handle;
    }
  }

  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return !!route.data['shouldReuse'];
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return !!route.data['shouldReuse'] && !!this.handlers[route.data['key']];
  }

  shouldReuseRoute(future: ActivatedRouteSnapshot, current: ActivatedRouteSnapshot): boolean {
    return !!future.data['shouldReuse'];
  }

}
```

**Comment by dongyuwei** [comment]
@volago Thank you! I'll try it in our project.

**Comment by inovozenko** [comment]
> I've solved this issue. There were two problems I encountered.
> 
> **1. Routing setup**
> 
> Previously we had such routing setup, which doesn't work
> 
> ```
> // routing module
> const routes: Routes = [
>   {
>     path: 'SomePath',
>     component: SomeComponent
>   }
> ];
> 
> @NgModule({
>   imports: [RouterModule.forChild(routes)],
>   exports: [RouterModule]
> })
> export class SomeRoutingModule { }
> 
> // lazy module
> @NgModule({
>   declarations: [
>     ... 
>   ],
>   imports: [
>     SomeRoutingModule,
>   ],  
> })
> export class SomeModule { }
> ```
> 
> Once we changed to setup bellow, most of our lazy loaded modules started to manage HMR correctly.
> 
> ```
> // routing module
> const routes: Routes = [
>   {
>     path: 'SomePath',
>     component: SomeComponent
>   }
> ];
> export const routing: ModuleWithProviders = RouterModule.forChild(routes);
> 
> // lazy module
> NgModule({
>   declarations: [ ... ],
>   imports: [
>     routing,
>     ...
>   ]
> })
> export class SomeModule {
>   constructor(moduleRef: NgModuleRef<SOmeModule>) {
>     if (environment.hmr) {
>       HmrModuleHelper.enableHmrRouterNgModule(module, moduleRef);      
>     }
>   }
> }
> 
> if (environment.hmr) {
>   HmrModuleHelper.enableHmrNodeModule(module);  
> }
> ```
> 
> **2. Route reusing strategy**
> After fixes in routing some lazy modules still didn't work. We found out that a cause was providing out own `RouteReuseStrategy`.
> 
> After all I didn't manage it to work. As workaround I disable reusing in dev mode.

Thanks! 
"1. Routing setup" was very useful!
